//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MMAWorkoutGenerator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXERCIS
    {
        public int exerciseID { get; set; }
        public string exerciseName { get; set; }
        public string exerciseDesc { get; set; }
    }
}
